#!/usr/bin/perl

# This file is part of local_nagios
# 
# local_nagios is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# local_nagios is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with local_nagios.  If not, see <http:# www.gnu.org/licenses/>.
# 
# Author: Michael Aherne
# Copyright 2014 University of Strathclyde

use strict;
use warnings;
use Getopt::Long;

my $MOODLE_HOME = '/C/Users/vas07101/dev/htdocs/moodle'; #'/var/www/beta';
my $PHP_COMMAND = 'php';

my $plugin;
my $service;
my $verbose = 0;

my $php_options = {
    'warning' => undef,
    'critical' => undef
};

my $service_options;

GetOptions('plugin=s' => \$plugin, 'service=s' => \$service, 'warning=s' => \$php_options->{'warning'}, 
    'critical=s' => \$php_options->{'critical'}, 'verbose+' => \$verbose, 'option=s%' => \$service_options);

die "plugin required" if not defined $plugin;
die "service required" if not defined $service;

my $command = "$PHP_COMMAND $MOODLE_HOME/local/nagios/cli/check.php --plugin=$plugin --service=$service";
for my $key ( keys %$php_options) {
    my $value = $php_options->{$key};
    if (defined $value) {
        $command .=  " --$key=$value";
    }
};

for my $key ( keys %$service_options) {
	my $value = $service_options->{$key};
	if (defined $value) {
		$command .=  " --$key=$value";
	}
}

my $result = qx/$command/;
print $result;

my $exit_code = $? >> 8;
exit($exit_code);
